CREATE TABLE IF NOT EXISTS public.technical_indicators_daily (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL,
    ticker text NOT NULL,
    timeframe text NOT NULL,
    period_length integer NOT NULL,
    event_date date NOT NULL,
    sma numeric,
    ema numeric,
    wma numeric,
    dema numeric,
    tema numeric,
    rsi numeric,
    standarddeviation numeric,
    williams numeric,
    adx numeric,
    raw_payload jsonb,
    CONSTRAINT unique_technical_indicators_daily UNIQUE (
        provider,
        ticker,
        timeframe,
        period_length,
        event_date
    )
);

CREATE INDEX IF NOT EXISTS idx_technical_indicators_daily_lookup
ON public.technical_indicators_daily (ticker, event_date DESC);

CREATE INDEX IF NOT EXISTS idx_technical_indicators_daily_period
ON public.technical_indicators_daily (timeframe, period_length, event_date DESC);

GRANT ALL ON TABLE public.technical_indicators_daily TO anon;
GRANT ALL ON TABLE public.technical_indicators_daily TO authenticated;
GRANT ALL ON TABLE public.technical_indicators_daily TO service_role;

GRANT ALL ON SEQUENCE public.technical_indicators_daily_id_seq TO anon;
GRANT ALL ON SEQUENCE public.technical_indicators_daily_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.technical_indicators_daily_id_seq TO service_role;
