CREATE TABLE IF NOT EXISTS public.fundamental_ratios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL,
    ticker text NOT NULL,
    company_name text,
    source_period_key text NOT NULL,
    period_type text NOT NULL,
    period_end_date date NOT NULL,
    filing_date date,
    available_at timestamp with time zone,
    fiscal_year integer,
    fiscal_quarter integer,
    calendar_year integer,
    calendar_quarter integer,
    current_ratio numeric,
    quick_ratio numeric,
    cash_ratio numeric,
    gross_margin numeric,
    operating_margin numeric,
    pretax_margin numeric,
    net_margin numeric,
    effective_tax_rate numeric,
    return_on_assets numeric,
    return_on_equity numeric,
    return_on_capital_employed numeric,
    debt_ratio numeric,
    debt_to_equity numeric,
    interest_coverage numeric,
    asset_turnover numeric,
    inventory_turnover numeric,
    receivables_turnover numeric,
    price_to_earnings numeric,
    price_to_book numeric,
    price_to_sales numeric,
    price_to_cash_flow numeric,
    price_to_free_cash_flow numeric,
    price_earnings_to_growth numeric,
    enterprise_value_multiple numeric,
    dividend_yield numeric,
    raw_payload jsonb,
    CONSTRAINT unique_fundamental_ratio UNIQUE (provider, ticker, source_period_key)
);

CREATE INDEX IF NOT EXISTS idx_fundamental_ratios_lookup
ON public.fundamental_ratios (ticker, available_at DESC, period_end_date DESC);

CREATE INDEX IF NOT EXISTS idx_fundamental_ratios_provider_period
ON public.fundamental_ratios (provider, ticker, period_type, period_end_date DESC);

GRANT ALL ON TABLE public.fundamental_ratios TO anon;
GRANT ALL ON TABLE public.fundamental_ratios TO authenticated;
GRANT ALL ON TABLE public.fundamental_ratios TO service_role;

GRANT ALL ON SEQUENCE public.fundamental_ratios_id_seq TO anon;
GRANT ALL ON SEQUENCE public.fundamental_ratios_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.fundamental_ratios_id_seq TO service_role;
