CREATE TABLE IF NOT EXISTS public.daily_stock_packages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_date date NOT NULL,
    ticker text NOT NULL,
    dataset_version text NOT NULL DEFAULT 'v1',
    scenario_id text NOT NULL DEFAULT 'baseline',
    manipulation_mode text NOT NULL DEFAULT 'clean',

    price_open numeric,
    price_high numeric,
    price_low numeric,
    price_close numeric,
    volume bigint,
    prev_price_close numeric,
    chg_open_vs_prev_close numeric,
    chg_open_vs_prev_close_pct numeric,
    chg_close_vs_open numeric,
    chg_close_vs_open_pct numeric,
    chg_close_vs_prev_close numeric,
    chg_close_vs_prev_close_pct numeric,

    sma numeric,
    ema numeric,
    wma numeric,
    dema numeric,
    tema numeric,
    rsi numeric,
    standarddeviation numeric,
    williams numeric,
    adx numeric,
    chg_sma numeric,
    chg_ema numeric,
    chg_rsi numeric,
    chg_williams numeric,
    chg_adx numeric,
    technical_trigger_flag boolean NOT NULL DEFAULT false,
    technical_trigger_reason text,

    fundamental_period_end_date date,
    current_ratio numeric,
    quick_ratio numeric,
    gross_margin numeric,
    operating_margin numeric,
    net_margin numeric,
    return_on_assets numeric,
    return_on_equity numeric,
    debt_to_assets_ratio numeric,
    debt_to_equity numeric,
    interest_coverage_ratio numeric,
    asset_turnover numeric,
    inventory_turnover numeric,
    receivables_turnover numeric,
    price_to_earnings numeric,
    price_to_book numeric,
    price_to_sales numeric,
    price_to_free_cash_flow numeric,
    enterprise_value_multiple numeric,
    dividend_yield numeric,
    prev_current_ratio numeric,
    chg_current_ratio numeric,
    prev_gross_margin numeric,
    chg_gross_margin numeric,
    prev_operating_margin numeric,
    chg_operating_margin numeric,
    prev_net_margin numeric,
    chg_net_margin numeric,
    prev_debt_to_equity numeric,
    chg_debt_to_equity numeric,
    filing_flag boolean NOT NULL DEFAULT false,
    filing_form text,
    latest_macro_indicator_name text,
    latest_macro_indicator_value numeric,
    fundamental_trigger_flag boolean NOT NULL DEFAULT false,
    fundamental_trigger_reason text,

    selected_news_id bigint,
    selected_news_title text,
    selected_news_content text,
    selected_news_published_at timestamp with time zone,
    daily_news_count integer NOT NULL DEFAULT 0,
    selected_general_news_id bigint,
    selected_general_news_title text,
    selected_general_news_content text,
    selected_general_news_published_at timestamp with time zone,
    daily_general_news_count integer NOT NULL DEFAULT 0,
    news_trigger_flag boolean NOT NULL DEFAULT false,
    news_trigger_reason text,

    source_refs jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),

    CONSTRAINT daily_stock_packages_unique
        UNIQUE (package_date, ticker, dataset_version, scenario_id, manipulation_mode)
);

CREATE INDEX IF NOT EXISTS idx_daily_stock_packages_date_ticker
ON public.daily_stock_packages (package_date, ticker);

CREATE INDEX IF NOT EXISTS idx_daily_stock_packages_variant
ON public.daily_stock_packages (dataset_version, scenario_id, manipulation_mode, package_date);

GRANT ALL ON TABLE public.daily_stock_packages TO anon;
GRANT ALL ON TABLE public.daily_stock_packages TO authenticated;
GRANT ALL ON TABLE public.daily_stock_packages TO service_role;

GRANT ALL ON SEQUENCE public.daily_stock_packages_id_seq TO anon;
GRANT ALL ON SEQUENCE public.daily_stock_packages_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.daily_stock_packages_id_seq TO service_role;
