CREATE TABLE IF NOT EXISTS public.manipulated_stock_news_daily (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL,
    title text NOT NULL,
    content text,
    publisher text,
    site text,
    falsity text NOT NULL,
    published_at timestamp with time zone NOT NULL,
    CONSTRAINT manipulated_stock_news_daily_unique
        UNIQUE (ticker, published_at, title)
);

GRANT ALL ON TABLE public.manipulated_stock_news_daily TO anon;
GRANT ALL ON TABLE public.manipulated_stock_news_daily TO authenticated;
GRANT ALL ON TABLE public.manipulated_stock_news_daily TO service_role;

GRANT ALL ON SEQUENCE public.manipulated_stock_news_daily_id_seq TO anon;
GRANT ALL ON SEQUENCE public.manipulated_stock_news_daily_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.manipulated_stock_news_daily_id_seq TO service_role;
