CREATE TABLE IF NOT EXISTS public.market_news_daily (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text,
    symbols text[] NOT NULL DEFAULT '{}'::text[],
    source_type text NOT NULL,
    title text NOT NULL,
    content text,
    published_at timestamp with time zone NOT NULL,
    publisher text,
    site text,
    dedupe_key text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT market_news_daily_source_type_check
        CHECK (source_type IN ('stock_news', 'press_release', 'general_news')),
    CONSTRAINT market_news_daily_dedupe_key_unique UNIQUE (dedupe_key)
);

CREATE INDEX IF NOT EXISTS idx_market_news_daily_ticker_time
ON public.market_news_daily (ticker, published_at DESC);

CREATE INDEX IF NOT EXISTS idx_market_news_daily_type_time
ON public.market_news_daily (source_type, published_at DESC);

CREATE INDEX IF NOT EXISTS idx_market_news_daily_symbols
ON public.market_news_daily USING gin (symbols);

GRANT ALL ON TABLE public.market_news_daily TO anon;
GRANT ALL ON TABLE public.market_news_daily TO authenticated;
GRANT ALL ON TABLE public.market_news_daily TO service_role;

GRANT ALL ON SEQUENCE public.market_news_daily_id_seq TO anon;
GRANT ALL ON SEQUENCE public.market_news_daily_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.market_news_daily_id_seq TO service_role;
