DROP TABLE IF EXISTS public.market_news_daily;

CREATE TABLE IF NOT EXISTS public.general_news_daily (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    content text,
    published_at timestamp with time zone NOT NULL,
    publisher text,
    site text,
    dedupe_key text NOT NULL UNIQUE,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_general_news_daily_time
ON public.general_news_daily (published_at DESC);

CREATE TABLE IF NOT EXISTS public.stock_news_daily (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL,
    symbols text[] NOT NULL DEFAULT '{}'::text[],
    title text NOT NULL,
    content text,
    published_at timestamp with time zone NOT NULL,
    publisher text,
    site text,
    dedupe_key text NOT NULL UNIQUE,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_stock_news_daily_ticker_time
ON public.stock_news_daily (ticker, published_at DESC);

CREATE INDEX IF NOT EXISTS idx_stock_news_daily_symbols
ON public.stock_news_daily USING gin (symbols);

CREATE TABLE IF NOT EXISTS public.press_releases_daily (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL,
    symbols text[] NOT NULL DEFAULT '{}'::text[],
    title text NOT NULL,
    content text,
    published_at timestamp with time zone NOT NULL,
    publisher text,
    site text,
    dedupe_key text NOT NULL UNIQUE,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_press_releases_daily_ticker_time
ON public.press_releases_daily (ticker, published_at DESC);

CREATE INDEX IF NOT EXISTS idx_press_releases_daily_symbols
ON public.press_releases_daily USING gin (symbols);

GRANT ALL ON TABLE public.general_news_daily TO anon;
GRANT ALL ON TABLE public.general_news_daily TO authenticated;
GRANT ALL ON TABLE public.general_news_daily TO service_role;
GRANT ALL ON TABLE public.stock_news_daily TO anon;
GRANT ALL ON TABLE public.stock_news_daily TO authenticated;
GRANT ALL ON TABLE public.stock_news_daily TO service_role;
GRANT ALL ON TABLE public.press_releases_daily TO anon;
GRANT ALL ON TABLE public.press_releases_daily TO authenticated;
GRANT ALL ON TABLE public.press_releases_daily TO service_role;

GRANT ALL ON SEQUENCE public.general_news_daily_id_seq TO anon;
GRANT ALL ON SEQUENCE public.general_news_daily_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.general_news_daily_id_seq TO service_role;
GRANT ALL ON SEQUENCE public.stock_news_daily_id_seq TO anon;
GRANT ALL ON SEQUENCE public.stock_news_daily_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.stock_news_daily_id_seq TO service_role;
GRANT ALL ON SEQUENCE public.press_releases_daily_id_seq TO anon;
GRANT ALL ON SEQUENCE public.press_releases_daily_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.press_releases_daily_id_seq TO service_role;
