CREATE TABLE IF NOT EXISTS public.market_prices_daily (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL,
    event_timestamp timestamp with time zone NOT NULL,
    price_open numeric,
    price_high numeric,
    price_low numeric,
    price_close numeric,
    volume bigint,
    CONSTRAINT unique_daily_entry UNIQUE (ticker, event_timestamp)
);

CREATE INDEX IF NOT EXISTS idx_daily_lookup
ON public.market_prices_daily (ticker, event_timestamp DESC);

GRANT ALL ON TABLE public.market_prices_daily TO anon;
GRANT ALL ON TABLE public.market_prices_daily TO authenticated;
GRANT ALL ON TABLE public.market_prices_daily TO service_role;

GRANT ALL ON SEQUENCE public.market_prices_daily_id_seq TO anon;
GRANT ALL ON SEQUENCE public.market_prices_daily_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.market_prices_daily_id_seq TO service_role;
