CREATE TABLE IF NOT EXISTS public.sec_filing_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL,
    cik bigint,
    company_name text,
    form text NOT NULL,
    filing_date date,
    acceptance_datetime timestamp with time zone,
    accession_number text NOT NULL,
    filename text,
    source_url text,
    submission_path text,
    document_path text,
    CONSTRAINT unique_sec_filing_event UNIQUE (accession_number)
);

CREATE INDEX IF NOT EXISTS idx_sec_filing_events_ticker_acceptance
ON public.sec_filing_events (ticker, acceptance_datetime DESC);

CREATE INDEX IF NOT EXISTS idx_sec_filing_events_ticker_filing_date
ON public.sec_filing_events (ticker, filing_date DESC);

CREATE INDEX IF NOT EXISTS idx_sec_filing_events_form
ON public.sec_filing_events (form);

GRANT ALL ON TABLE public.sec_filing_events TO anon;
GRANT ALL ON TABLE public.sec_filing_events TO authenticated;
GRANT ALL ON TABLE public.sec_filing_events TO service_role;

GRANT ALL ON SEQUENCE public.sec_filing_events_id_seq TO anon;
GRANT ALL ON SEQUENCE public.sec_filing_events_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.sec_filing_events_id_seq TO service_role;
