CREATE TABLE IF NOT EXISTS public.technical_indicators_daily (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL,
    ticker text NOT NULL,
    timeframe text NOT NULL,
    period_length integer NOT NULL,
    event_date date NOT NULL,
    sma numeric,
    ema numeric,
    wma numeric,
    dema numeric,
    tema numeric,
    rsi numeric,
    standarddeviation numeric,
    williams numeric,
    adx numeric,
    raw_payload jsonb,
    CONSTRAINT unique_technical_indicators_daily UNIQUE (
        provider,
        ticker,
        timeframe,
        period_length,
        event_date
    )
);

CREATE INDEX IF NOT EXISTS idx_technical_indicators_daily_lookup
ON public.technical_indicators_daily (ticker, event_date DESC);

CREATE INDEX IF NOT EXISTS idx_technical_indicators_daily_period
ON public.technical_indicators_daily (timeframe, period_length, event_date DESC);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'technical_indicator_series'
    ) THEN
        INSERT INTO public.technical_indicators_daily (
            provider,
            ticker,
            timeframe,
            period_length,
            event_date,
            sma,
            ema,
            wma,
            dema,
            tema,
            rsi,
            standarddeviation,
            williams,
            adx,
            raw_payload
        )
        SELECT
            provider,
            ticker,
            timeframe,
            period_length,
            event_date,
            max(value) FILTER (WHERE indicator = 'sma'),
            max(value) FILTER (WHERE indicator = 'ema'),
            max(value) FILTER (WHERE indicator = 'wma'),
            max(value) FILTER (WHERE indicator = 'dema'),
            max(value) FILTER (WHERE indicator = 'tema'),
            max(value) FILTER (WHERE indicator = 'rsi'),
            max(value) FILTER (WHERE indicator = 'standarddeviation'),
            max(value) FILTER (WHERE indicator = 'williams'),
            max(value) FILTER (WHERE indicator = 'adx'),
            jsonb_object_agg(indicator || ':' || component, raw_payload)
        FROM public.technical_indicator_series
        GROUP BY provider, ticker, timeframe, period_length, event_date
        ON CONFLICT (provider, ticker, timeframe, period_length, event_date)
        DO UPDATE SET
            sma = EXCLUDED.sma,
            ema = EXCLUDED.ema,
            wma = EXCLUDED.wma,
            dema = EXCLUDED.dema,
            tema = EXCLUDED.tema,
            rsi = EXCLUDED.rsi,
            standarddeviation = EXCLUDED.standarddeviation,
            williams = EXCLUDED.williams,
            adx = EXCLUDED.adx,
            raw_payload = EXCLUDED.raw_payload;

        DROP TABLE public.technical_indicator_series;
    END IF;
END $$;

GRANT ALL ON TABLE public.technical_indicators_daily TO anon;
GRANT ALL ON TABLE public.technical_indicators_daily TO authenticated;
GRANT ALL ON TABLE public.technical_indicators_daily TO service_role;

GRANT ALL ON SEQUENCE public.technical_indicators_daily_id_seq TO anon;
GRANT ALL ON SEQUENCE public.technical_indicators_daily_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.technical_indicators_daily_id_seq TO service_role;
