CREATE TABLE IF NOT EXISTS public.economic_indicators (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL,
    country text NOT NULL,
    indicator_name text NOT NULL,
    event_date date NOT NULL,
    value numeric,
    raw_payload jsonb,
    CONSTRAINT unique_economic_indicator UNIQUE (
        provider,
        country,
        indicator_name,
        event_date
    )
);

CREATE INDEX IF NOT EXISTS idx_economic_indicators_lookup
ON public.economic_indicators (indicator_name, event_date DESC);

CREATE INDEX IF NOT EXISTS idx_economic_indicators_country
ON public.economic_indicators (country, indicator_name, event_date DESC);

GRANT ALL ON TABLE public.economic_indicators TO anon;
GRANT ALL ON TABLE public.economic_indicators TO authenticated;
GRANT ALL ON TABLE public.economic_indicators TO service_role;

GRANT ALL ON SEQUENCE public.economic_indicators_id_seq TO anon;
GRANT ALL ON SEQUENCE public.economic_indicators_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.economic_indicators_id_seq TO service_role;
